name: Test Build
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - main

jobs:
  armhf:
    name: Test build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Deps
      run: |
        sudo apt install gcc-12 g++-12 libnm-dev libglib2.0-dev -y
    - name: Build
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..  -DCMAKE_CXX_COMPILER=$(which g++-12) \
                  -DCMAKE_C_COMPILER=$(which gcc-12)
        make -j$(nproc)
