name: Test Build
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  armhf:
    name: build-armhf
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Deps
      run: sudo apt install gcc-8-arm-linux-gnueabihf g++-8-arm-linux-gnueabihf
    - name: Build
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..  -DCMAKE_CXX_COMPILER=$(which arm-linux-gnueabihf-g++-8) \
                  -DCMAKE_C_COMPILER=$(which arm-linux-gnueabihf-gcc-8) \
                  -DARMHF_DEB=ON \
                  -DARCHITECTURE="armhf"
        make -j$(nproc)
